version: '3'

networks:
  timeout_network:

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react-app
    networks:
      - timeout_network

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    volumes:
      - ./my-react-app:/app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - timeout_network
    services:
  authservicenodeforgit:
    image: authservicenodeforgit
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3006:3006
    networks:
       TimeOut-network:
       driver: bridge  
